In [1]:
# Numpy is linear algebra libeary in python 

In [2]:
import numpy as np 

In [3]:
list1 = [1,2,3,4,5]

In [4]:
list1

[1, 2, 3, 4, 5]

In [5]:
type(list1) 

list

In [7]:
x = np.array(list1)  

In [8]:
x 

array([1, 2, 3, 4, 5])

In [9]:
type(x) 

numpy.ndarray

In [12]:
# 2 Dimensional Array 

In [13]:
list2 = [[1,2,3],[4,5,6]] 

In [14]:
arr = np.array(list2) 

In [15]:
arr 

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
type(arr) 

numpy.ndarray

In [17]:
# Accessing 2d Array element

In [19]:
arr[0,0]  

1

In [20]:
arr[1,1] 

5

In [22]:
arr[1,2]  

6

In [23]:
arr[0,2] 

3

In [25]:
arr[0,1]  

2

In [27]:
arr[0,]        # Accessing all elements of 0th row

array([1, 2, 3])

In [29]:
arr[1,]        # Accessing all element of 1st row 

array([4, 5, 6])

In [33]:
arr[ :,0]     # Accessing all element of 0th column of matrix 

array([1, 4])

In [34]:
arr[:,1]     # Accessing all element of 1st column matrix

array([2, 5])

In [35]:
arr[1,:]    # Accessing all element of 1st row of matrix 

array([4, 5, 6])

In [38]:
np.zeros((3,3))     # genrate zero matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones((3,3))     # genrate ones matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.arange(31,41)  

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [44]:
np.arange(31,41,2) 

array([31, 33, 35, 37, 39])

In [48]:
np.linspace(0,5,10)     # genrate 2 dimensional matrix element between 0 to 5 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [52]:
np.random.rand(3)      # genrate 1 dimensional random genrated array

array([0.30578152, 0.4857504 , 0.74766629])

In [53]:
np.random.rand(3,3)    # genrate 2 dimensional random no matrix 

array([[0.07959094, 0.89770563, 0.94935705],
       [0.64737826, 0.34999936, 0.79523791],
       [0.4389436 , 0.27516028, 0.29446679]])

In [54]:
np.random.randn(3)   # genrate 3 random no of standard normal distibution

array([0.34075651, 2.40238846, 1.98593674])

In [55]:
np.random.randn(2,2)  # genrate 2D matrix of randomly genrated no of Standard normal distribution

array([[-0.70080256, -0.9694372 ],
       [ 0.08961134,  1.5274329 ]])

In [57]:
np.random.randint(0,11) # genrate random integer between 0 to 11

5

In [59]:
np.random.randint(0,11,3) # randomly genrate 3 integers  

array([6, 9, 2])

In [60]:
a = np.random.randint(0,20,9) 

In [61]:
a 

array([ 7, 17, 15, 12,  8,  4,  0, 14,  8])

In [62]:
a.reshape(3,3)   # convert 1D a array into 2D matrix 

array([[ 7, 17, 15],
       [12,  8,  4],
       [ 0, 14,  8]])

In [64]:
a.max()         # getting max value of the a array 

17

In [65]:
a.argmax()     # getting index of max value of the array 

1

In [66]:
a.max()         # getting max value of the a array a.min()       

17

In [67]:
a.argmin()     # getting index of min value of the array

6